name: Transform Design Tokens

on:
  workflow_dispatch:
  pull_request:

jobs:
  generate_tokens:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: markacianfrani/token-bot-action@v0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        files: tokens/base.*.json
